---
name: projectify-compose
volumes:
    postgres-data:
    keydb-data:
services:
    web:
        build:
            context: .
            dockerfile: projectify-revproxy.Dockerfile
        ports:
            - "5000:5000"
        environment:
            PORT: "5000"
            FRONTEND_HOST: frontend
            FRONTEND_PORT: "5001"
            BACKEND_HOST: backend
            BACKEND_PORT: 5002
        depends_on:
            - backend
    frontend:
        build:
            dockerfile: projectify-frontend.Dockerfile
        environment:
            SVELTE_KIT_PORT: 5001
    backend:
        build:
            dockerfile: projectify-backend.Dockerfile
        environment: &backend-env
            SECRET_KEY: do-not-use
            # Networking
            PORT: "5002"
            ALLOWED_HOSTS: "localhost"
            # Settings
            DJANGO_SETTINGS_MODULE: projectify.settings.production
            DJANGO_CONFIGURATION: Production
            # Database
            DATABASE_URL: postgres://projectify:projectify@postgres:5432/projectify
            REDIS_TLS_URL: redis://keydb:6379/0
            # Frontend
            FRONTEND_URL: http://localhost:5000
            # Stripe
            STRIPE_PUBLISHABLE_KEY: pk_test_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            STRIPE_SECRET_KEY: sk_test_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            STRIPE_PRICE_OBJECT: price_XXXXXXXXXXXXXXXXXXXXXXXX
            STRIPE_ENDPOINT_SECRET: whsec_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            # Mailgun
            MAILGUN_API_KEY: XXXX
            MAILGUN_DOMAIN: localhost
        depends_on:
            - keydb
            - postgres
            - worker
        ports:
    migrate_backend:
        build:
            dockerfile: projectify-manage.Dockerfile
        environment: *backend-env
        command: migrate
        depends_on:
            - postgres
    worker:
        build:
            dockerfile: projectify-celery.Dockerfile
        environment: *backend-env
        depends_on:
            - keydb
            - postgres
    keydb:
        image: docker.io/eqalpha/keydb
        volumes:
            - keydb-data:/data
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          interval: 1s
          timeout: 3s
          retries: 30
    postgres:
        image: docker.io/postgres
        restart: always
        shm_size: 128mb
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: projectify
            POSTGRES_USER: projectify
            POSTGRES_PASSWORD: projectify
            PGDATA: /var/lib/postgresql/data/pgdata
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U projectify"]
          interval: 30s
          timeout: 30s
          retries: 3
