---
name: projectify-compose
volumes:
    postgres-data:
    keydb-data:
services:
    web:
        image: projectify-revproxy:latest
        restart: always
        ports:
            - "5000:80"
        environment:
            HOST: "localhost"
            PORT: "80"
            FRONTEND_HOST: frontend
            FRONTEND_PORT: "5001"
            BACKEND_HOST: backend
            BACKEND_PORT: 5002
        depends_on:
            - backend
    frontend:
        image: projectify-frontend-node:latest
        restart: always
        environment:
            SVELTE_KIT_PORT: 5001
    backend:
        image: projectify-backend:latest
        restart: always
        environment: &backend-env
            SECRET_KEY: do-not-use
            # Networking
            PORT: "5002"
            ALLOWED_HOSTS: "localhost"
            # Settings
            DJANGO_SETTINGS_MODULE: projectify.settings.production
            DJANGO_CONFIGURATION: Production
            # Database
            DATABASE_URL: postgres://projectify:projectify@postgres:5432/projectify
            REDIS_TLS_URL: redis://keydb:6379/0
            # Frontend
            FRONTEND_URL: http://localhost:5000
            # Stripe
            STRIPE_PUBLISHABLE_KEY: pk_test_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            STRIPE_SECRET_KEY: sk_test_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            STRIPE_PRICE_OBJECT: price_XXXXXXXXXXXXXXXXXXXXXXXX
            STRIPE_ENDPOINT_SECRET: whsec_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            # Mailgun
            MAILGUN_API_KEY: XXXX
            MAILGUN_DOMAIN: localhost
        depends_on:
            - keydb
            - postgres
            - worker
        ports:
    migrate_backend:
        image: projectify-backend:latest
        restart: always
        environment: *backend-env
        command: projectify-manage migrate
        depends_on:
            - postgres
    worker:
        image: projectify-celery:latest
        restart: always
        environment: *backend-env
        depends_on:
            - keydb
            - postgres
    keydb:
        image: docker.io/eqalpha/keydb:latest
        restart: always
        volumes:
            - keydb-data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 1s
            timeout: 3s
            retries: 30
    postgres:
        image: docker.io/postgres:15
        restart: always
        shm_size: 128mb
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: projectify
            POSTGRES_USER: projectify
            POSTGRES_PASSWORD: projectify
            PGDATA: /var/lib/postgresql/data/pgdata
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U projectify"]
            interval: 30s
            timeout: 30s
            retries: 3
