[build]
base = "frontend"
command = "npm run build"
# Apparently netlify automatically assumes this to be relative to the base
# folder
publish = "build"

[build.environment]
NODE_ENV = "production"

[[redirects]]
from = "/*"
to = "/fallback.html"
status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'none'"
