# SPDX-FileCopyrightText: 2024 JWP Consulting GK
#
# SPDX-License-Identifier: AGPL-3.0-or-later

[build]
base = "frontend"
command = "npm run build"
# Apparently netlify automatically assumes this to be relative to the base
# folder
publish = "build"

[build.environment]
NODE_ENV = "production"
VITE_PROJECTIFY_DOMAIN = "https://www.projectifyapp.com"
PROJECTIFY_FRONTEND_ADAPTER = "static"

[[redirects]]
from = "/*"
to = "/fallback.html"
status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'none'"
