[tool.black]
line-length=79

[tool.isort]
default_section = "FIRSTPARTY"
force_grid_wrap = 1
include_trailing_comma = true
indent = '    '
line_length = 79
lines_after_imports = 2
multi_line_output = 3
sections = ["STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_django = ["django"]
known_third_party = [
    "asgiref",
    "channels",
    "channels_graphql_ws",
    "strawberry",
    "pytest",
    "rest_framework"
]
known_first_party = ["user"]

[tool.mypy]
mypy_path = [
    "mypy/stubs",
]
# https://mypy.readthedocs.io/en/stable/existing_code.html#introduce-stricter-options
# Start off with these - done!
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true

# Getting these passing should be easy - done!
strict_equality = true
strict_concatenate = true

# Strongly recommend enabling this one as soon as you can - done!
check_untyped_defs = true

# These shouldn't be too much additional work, but may be tricky to
# get passing if you use a lot of untyped libraries
# Therefore: Not done yet Justus 2023-05-20
# Not possible because the factory decorator is not typed
# disallow_untyped_decorators = true
# Not possible because of factory, django_extensions, channels and rest_framework
# disallow_subclassing_any = true
disallow_any_generics = true

# These next few are various gradations of forcing use of type annotations
# done!
disallow_untyped_calls = true
disallow_incomplete_defs = true
disallow_untyped_defs = true

# This one isn't too hard to get passing, but return on investment is lower
no_implicit_reexport = true

# This one can be tricky to get passing if you use a lot of untyped libraries
warn_return_any = true

# Library imports
[[tool.mypy.overrides]]
module = "celery.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "cloudinary.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "channels.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "django.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "dj_database_url.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "factory.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pgtrigger.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "redis.asyncio"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "rest_framework.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "rules"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "stripe"
ignore_missing_imports = true

# Our own modules
[[tool.mypy.overrides]]
module = [
    "corporate.schema.types",
    "corporate.test.*",
    "premail.test.*",
    "projectify.test.*",
    "user.schema.mutation",
    "user.schema.types",
    "user.test.*",
    "workspace.schema.mutation",
    "workspace.schema.types",
    "workspace.test.*",
]
ignore_errors = true

# Here is where we get strict again
# [[tool.mypy.overrides]]
# module = [
#     "blog.*",
#     "corporate.*",
#     "premail.*",
#     "projectify.*",
#     "user.*",
#     "workspace.*",
# ]
