[tool.black]
line-length=79

[tool.isort]
default_section = "FIRSTPARTY"
force_grid_wrap = 1
include_trailing_comma = true
indent = '    '
line_length = 79
lines_after_imports = 2
multi_line_output = 3
sections = ["STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_django = ["django"]
known_third_party = [
    "asgiref",
    "channels",
    "channels_graphql_ws",
    "strawberry",
    "pytest",
    "rest_framework"
]
known_first_party = ["user"]

[tool.mypy]
mypy_path = [
    "mypy/stubs",
]
strict = true

# Library imports
[[tool.mypy.overrides]]
module = [
    "celery.*",
    "cloudinary.*",
    "dj_database_url.*",
    "pgtrigger.*",
]
ignore_missing_imports = true

# Our own modules
[[tool.mypy.overrides]]
module = [
    "workspace.schema.mutation",
]
disable_error_code = ["return-value"]

[[tool.mypy.overrides]]
module = [
    "premail.tasks",
]
disallow_untyped_decorators = false

[[tool.mypy.overrides]]
module = [
    "corporate.schema.types",
    "workspace.schema.types",
]
strict_equality = false

[[tool.mypy.overrides]]
module = [
    "workspace.schema.types",
]
warn_return_any = false
disable_error_code = ["attr-defined", "return-value"]

[[tool.mypy.overrides]]
module = [
    "corporate.test.*",
    "workspace.test.schema.*",
    "workspace.test.test_models",
    "workspace.test.test_migrations",
    "user.test.schema.*",
    "user.test.test_models",
    "user.test.test_emails",
    "premail.test.*",
]
disallow_untyped_defs = false

[tool.pyright]
stubPath = "mypy/stubs"
typeCheckingMode = "strict"
typeshedPath = ""
