[tool.black]
line-length=79

[tool.isort]
default_section = "FIRSTPARTY"
force_grid_wrap = 1
include_trailing_comma = true
indent = '    '
line_length = 79
lines_after_imports = 2
multi_line_output = 3
sections = ["STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_django = ["django"]
known_third_party = [
    "asgiref",
    "channels",
    "channels_graphql_ws",
    "strawberry",
    "pytest",
    "rest_framework"
]
known_first_party = ["user"]

[tool.mypy]
mypy_path = [
    "mypy/stubs",
]
strict = true
exclude = [".git", "__pycache__", "docs", "whitelist.py"]

# Library imports
[[tool.mypy.overrides]]
module = [
    "cloudinary.*",
    "pgtrigger.*",
]
ignore_missing_imports = true

# Our own modules
[[tool.mypy.overrides]]
module = [
    "workspace.schema.mutation",
]
disable_error_code = ["return-value"]

[[tool.mypy.overrides]]
module = [
    "premail.tasks",
]
disallow_untyped_decorators = false

[[tool.mypy.overrides]]
module = [
    "corporate.schema.types",
    "workspace.schema.types",
]
strict_equality = false

[[tool.mypy.overrides]]
module = [
    "workspace.schema.types",
]
warn_return_any = false
disable_error_code = ["attr-defined", "return-value"]

[[tool.mypy.overrides]]
module = [
    "corporate.test.*",
    "workspace.test.schema.*",
    "workspace.test.test_migrations",
    "user.test.schema.*",
    "user.test.test_models",
    "user.test.test_emails",
    "premail.test.*",
]
disallow_untyped_defs = false

[tool.pyright]
stubPath = "mypy/stubs"
typeCheckingMode = "strict"
typeshedPath = ""

[tool.poetry]
name = "Projectify Backend"
version = "0.1.0"
description = ""
authors = ["Justus Perlwitz <justus@jwpconsulting.net>"]
readme = "README.md"

[tool.poetry.dependencies]
celery = {extras = ["redis"], version = "~5.2.7"}
channels = {version = "~4.0.0", extras = ["daphne"]}
channels-redis = "~4.0.0"
dj-database-url = "~2.1.0"
django = "~4.2.3"
django-anymail = {extras = ["mailgun"], version = "~8.6"}
django-celery-results = "~2.4.0"
django-cloudinary-storage = "~0.3.0"
django-configurations = "^2.4.1"
django-cors-headers = "~3.13.0"
django-extensions = "~3.2.0"
django-ordered-model = "~3.6"
django-pgtrigger = "~2.4.1"
djangorestframework = "^3"
gunicorn = "~20.1.0"
newrelic = "~8"
pillow = "~10.0.1"
psycopg2 = "~2.9.3"
python = "~3.11"
python-dotenv = "~0.20.0"
redis = "~4.5.4"
rules = "~3.3"
strawberry-graphql = "~0.205.0"
strawberry-graphql-django = "~0.16.1"
stripe = "~3.5.0"
uvicorn = "~0.17.6"
websockets = "~10.3"
whitenoise = "~6.2.0"

# Might be worth using seeddb without factory-boy and tqdm, IDK
factory-boy = "~3.2.1"
tqdm = "~4.64.0"

# Strictly only used for local development
[tool.poetry.group.dev]

[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "~3.5.0"
ipython = "~8.10.0"
pdbpp = "~0.10.3"
pyright = "~1.1.318"

[tool.poetry.group.test]

[tool.poetry.group.test.dependencies]
black = "~22.6.0"
celery-types = "~0.20.0"
django-test-migrations = "~1.2.0"
django-types = "~0"
flake8 = "~4.0.1"
flake8-black = "~0.3.3"
flake8-docstrings = "~1.6.0"
flake8-isort = "~4.1.1"
isort = "~5.10.1"
mypy = "~1.4.1"
pytest = "~7.2.1"
pytest-asyncio = "~0.20.3"
pytest-celery = "~0.0.0"
pytest-django = "~4.5.2"
pytest-xdist = {extras = ["psutil"], version = "~3.3.1"}
types-redis = "~4.6.0.5"
types-stripe = "~3.5.2.14"
types-tqdm = "~4.66.0.2"
vulture = "^2.9.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.vulture]
ignore_decorators = ["@receiver", "@admin.register"]
exclude = [
    "apps.py",
    "conftest.py",
    "settings",
    "schema",
    "migrations",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "projectify.settings.test"
DJANGO_CONFIGURATION = "Test"
asyncio_mode = "auto"
junit_family = "xunit1"
filterwarnings = [
    "error",
    # Wait for celery to get kombu upgraded
    "ignore:SelectableGroups dict interface is deprecated. Use select.:DeprecationWarning",
    # Some issue with daphne or twisted
    "ignore:'cgi' is deprecated and slated for removal in Python 3.13:DeprecationWarning",
    # We will stop using strawberry eventually
    "ignore:Argument name-based matching of 'info' is deprecated:DeprecationWarning",
    # Some issue with django-configurations
    "ignore:The USE_DEPRECATED_PYTZ setting:django.utils.deprecation.RemovedInDjango50Warning",
    "ignore:The USE_L10N setting:django.utils.deprecation.RemovedInDjango50Warning",
    "ignore:The CSRF_COOKIE_MASKED transitional setting:django.utils.deprecation.RemovedInDjango50Warning",
    # Again, another issue with djagno-configurations
    # https://github.com/jazzband/django-configurations/issues/367
    "ignore:the imp module is deprecated:DeprecationWarning",
    "ignore:ConfigurationImporter:ImportWarning",
    "ignore:ConfigurationLoader:ImportWarning",
]
