---
networks:
  podman:
    external: true
services:
    web:
        image: localhost/projectify-revproxy:latest
    backend:
        image: localhost/projectify-backend:latest
        environment: &backend-env
            SECRET_KEY: do-not-use
            # Networking
            PORT: "8000"
            ALLOWED_HOSTS: "localhost"
            INTERNAL_IPS: "127.0.0.1"
            # Settings
            DJANGO_SETTINGS_MODULE: projectify.settings.production
            DJANGO_CONFIGURATION: Production
            # Database
            DATABASE_URL: postgres://localhost:5432/projectify
            REDIS_TLS_URL: redis://keydb:12111/0
            # Frontend
            FRONTEND_URL: http://localhost
            # Stripe
            STRIPE_PUBLISHABLE_KEY: pk_test_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            STRIPE_SECRET_KEY: sk_test_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            STRIPE_PRICE_OBJECT: price_XXXXXXXXXXXXXXXXXXXXXXXX
            STRIPE_ENDPOINT_SECRET: whsec_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            # Mailgun
            MAILGUN_API_KEY: XXXX
            MAILGUN_DOMAIN: localhost
        depends_on:
            - keydb
    worker:
        image: localhost/projectify-celery:latest
        environment: *backend-env
        depends_on:
            - keydb
        networks:
            - podman
    keydb:
        image: docker.io/eqalpha/keydb
        ports:
            # Something about rootless network causes trouble here
            - "12111:6379"
        networks:
            - podman
