version: 2.1
executors:
    node:
        docker:
            - image: cimg/node:16.15.0
commands:
    install_dependencies:
        description: Install dependencies
        steps:
            - run:
                  name: npm ci
                  command: npm ci
jobs:
    check:
        executor: node
        steps:
            - checkout
            - restore_cache:
                  key: npm-cache-v1-{{ checksum "package-lock.json" }}
            - install_dependencies
            - save_cache:
                  key: npm-cache-v1-{{ checksum "package-lock.json" }}
                  paths:
                      - ~/.npm
            - run:
                  name: Run check
                  command: npm run check
    lint:
        executor: node
        steps:
            - checkout
            - restore_cache:
                  key: npm-cache-v1-{{ checksum "package-lock.json" }}
            - install_dependencies
            - run:
                  name: Run lint
                  command: npm run lint
workflows:
    test_all:
        jobs:
            - check
            - lint
