name: Initialize nix docker build
inputs:
    build_target:
        required: true
runs:
    using: "composite"
    steps:
        - uses: achix/install-nix-action@v27
          with:
              nix_path: nixpkgs=channel:nixos-24.05

        - name: Authenticate with skopeo
          run:
              nix run .#skopeo -- login ghcr.io --username=${{ github.actor }} --password='${{ secrets.GITHUB_TOKEN }}'
              docker://ghcr.io/${{ github.repository }}
        - name: Build image
          run: nix build --out-link result.tar.gz ${{ inputs.build_target }}
        - name: Push with skopeo
          run: nix run .#skopeo -- copy docker-archive:result.tar.gz docker://ghcr.io/${{ github.repository }}
