name: Initialize nix docker build
inputs:
    build_target:
        required: true
    username:
        required: true
    password:
        required: true
runs:
    using: "composite"
    steps:
        - uses: cachix/install-nix-action@v27
          with:
              nix_path: nixpkgs=channel:nixos-24.05
        - uses: DeterminateSystems/magic-nix-cache-action@v7
        - name: Authenticate with skopeo
          run:
              nix run .#skopeo -- login --username=${{ inputs.username }} --password='${{ inputs.password }}' ghcr.io
          shell: bash
        - name: Build image
          run: nix build --out-link result.tar.gz ${{ inputs.build_target }}
          shell: bash
        - name: Push with skopeo
          run: nix run .#skopeo -- copy docker-archive:result.tar.gz docker://ghcr.io/${{ github.repository }}
          shell: bash
