# SPDX-FileCopyrightText: 2024 JWP Consulting GK
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1

[[annotations]]
path = ["*.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 JWP Consulting GK"
SPDX-License-Identifier = "AGPL-3.0-or-later"
