name: Build all docker images

on:
    pull_request:
jobs:
    projectify-backend:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: docker/setup-buildx-action@v3
        -
            uses: docker/build-push-action@v6
            with:
                push: false
                load: true
                file: projectify-backend.Dockerfile
                cache-from: type=gha
                cache-to: type=gha,mode=max
                tags: projectify-backend:latest
        -
            uses: docker/build-push-action@v6
            with:
                push: false
                load: true
                file: projectify-celery.Dockerfile
                cache-from: type=gha
                cache-to: type=gha,mode=max
                tags: projectify-celery:latest
        -
            uses: docker/build-push-action@v6
            with:
                push: false
                load: true
                file: projectify-manage.Dockerfile
                cache-from: type=gha
                cache-to: type=gha,mode=max
                tags: projectify-manage:latest
        -
            uses: docker/build-push-action@v6
            with:
                push: false
                load: true
                file: projectify-frontend.Dockerfile
                cache-from: type=gha
                cache-to: type=gha,mode=max
                tags: projectify-frontend:latest
        -
            uses: docker/build-push-action@v6
            with:
                push: false
                load: true
                file: projectify-revproxy.Dockerfile
                cache-from: type=gha
                cache-to: type=gha,mode=max
                tags: projectify-revproxy:latest
