name: Build all containers using Nix

on:
    pull_request:
jobs:
    projectify-backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/set-up-nix-docker
              with:
                  build_target: .#projectify-backend-container
    projectify-celery:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/set-up-nix-docker
              with:
                  build_target: .#projectify-celery-container
    projectify-frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/set-up-nix-docker
              with:
                  build_target: .#projectify-frontend-container
    projectify-revproxy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/set-up-nix-docker
              with:
                  build_target: .#projectify-revproxy-container
