name: Build all containers using Nix

on:
    pull_request:
jobs:
    projectify-backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/set-up-nix-docker
              with:
                  build_target: .#projectify-backend-container
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
    projectify-celery:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/set-up-nix-docker
              with:
                  build_target: .#projectify-celery-container
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
    projectify-frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/set-up-nix-docker
              with:
                  build_target: .#projectify-frontend-container
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
    projectify-revproxy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/set-up-nix-docker
              with:
                  build_target: .#projectify-revproxy-container
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
