name: Build all containers using Nix

on:
    pull_request:
    push:
        branches:
            - "main"
jobs:
    projectify-backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/set-up-nix-docker
              with:
                  build_target: .#projectify-backend-container
                  package_name: projectify-backend
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
    projectify-celery:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/set-up-nix-docker
              with:
                  build_target: .#projectify-celery-container
                  package_name: projectify-celery
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
    projectify-frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/set-up-nix-docker
              with:
                  build_target: .#projectify-frontend-node-container
                  package_name: projectify-frontend-node
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
    projectify-revproxy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/set-up-nix-docker
              with:
                  build_target: .#projectify-revproxy-container
                  package_name: projectify-revproxy
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
