name: Build all containers using Nix

on:
    pull_request:
jobs:
    projectify-backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: achix/install-nix-action@v27
              with:
                  nix_path: nixpkgs=channel:nixos-24.05
            - run: nix build .#projectify-backend-container
    projectify-celery:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: achix/install-nix-action@v27
              with:
                  nix_path: nixpkgs=channel:nixos-24.05
            - run: nix build .#projectify-celery-container
    projectify-frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: achix/install-nix-action@v27
              with:
                  nix_path: nixpkgs=channel:nixos-24.05
            - run: nix build .#projectify-frontend-node-container
    projectify-revproxy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: achix/install-nix-action@v27
              with:
                  nix_path: nixpkgs=channel:nixos-24.05
            - run: nix build .#projectify-revproxy-container
