name: Build docker image

on:
    push:
    pull_request:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
        -
            uses: docker/build-push-action@v6
            with:
                context: "{{defaultContext}}:backend"
                push: false
                load: true
                file: projectify-backend.Dockerfile
                cache-from: type=gha
                cache-to: type=gha,mode=max
