name: "Test"
on:
    push:
    pull_request:
jobs:
    tests:
        defaults:
            run:
                working-directory: backend
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: cachix/install-nix-action@v27
          with:
            nix_path: nixpkgs=channel:nixos-24.05
        - run: nix build .#projectify-backend
